llm:
  model: "claude-3-7-sonnet-20250219"
  max_tokens_per_request: 4096
  temperature: 0.7
  prompts:
    system: |
      You are an expert in web security and penetration testing with over 20 years of experience.
      Your new job is to help hackers find vulnerabilities in web applications. Every successful finding could result in a $100,000 reward. You need to think outside of the box, and catch all small details that could be exploited. Make sure to ask questions if the hacker forgot to include any details.
    query: |
      The team is focusing on vulnerabilities surrounding OAuth and SAML. This includes any vulnerability class that could be exploited through misconfigured OAuth/SAML such as xss, csrf, etc. 
      Try to chain together multiple vulnerabilities to find a more complex exploit when possible.
      Please answer the following question, with the provided in-house documentation context as well as your own expertise.
      If the context contains relevant information, cite the specific source.
      If the context doesn't contain the needed information, say so clearly.

      Documentation Context:
      {context}

      Question: {query}

chunking:
  chunk_size: 800
  chunk_overlap: 200
  max_chunks: 15  # Maximum chunks to send to LLM
  min_relevance: 0.67  # Minimum relevance score (0-1) to include chunk

chat:
  max_history: 10

scraping:
  delay: 3  # Delay between requests to same domain
  js_sites:
    hackerone.com:
  headers:
    User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
  timeouts:
    connect: 5
    read: 15
    scrape: 30

# Device settings
device:
  type: "mps"  # Options: "cuda" (for NVIDIA), "rocm" (for AMD), "cpu", "mps" (Apple Silicon)
